
stages:
    - deps
    - check
    - build
    - version
    - publish

cache:
  paths:
    - /root/.cache/composer/

vendor:
    stage: deps
    image: cyberpearuk/php-build-docker
    only:
        refs:
            - branches
    script:
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install
    artifacts:
        expire_in: 1 day
        paths:
            - vendor/

phpcs:
    stage: check
    image: cyberpearuk/php-build-docker
    only:
        refs:
            - branches
    needs:
        - job: vendor
          artifacts: true
    script:
        - vendor/bin/phpcs -n -s --standard=php-standards ./src

phan:
    stage: check
    image: jbuncle/php-build-phan
    only:
        refs:
            - branches
    needs:
        - job: vendor
          artifacts: true
    script:
        - phan --target-php-version=7.4
        - phan --target-php-version=8.0

version:
    stage: version
    image: jbuncle/php-autosemver
    needs:
        - job: phpcs
          artifacts: false
        - job: phan
          artifacts: false
    script:
        - echo "VERSION=$(next-version)" >> build.env
        - cat build.env
    artifacts:
        reports:
            dotenv: build.env
    only:
        refs:
            - master

git-tag:
    stage: publish
    image: jbuncle/php-autosemver
    needs:
        - job: version
          artifacts: true
    script:
        - git-tag ${VERSION}
    only:
        refs:
            - master

nexus-publish:
    stage: publish
    image: jbuncle/composer-nexus-upload
    needs:
        - job: version
          artifacts: true
    script:
        - nexus-upload
         --repository=https://nexus.jbuncle.co.uk/repository/composer-private/ 
         --username=composer-publisher 
         --password=$NEXUS_PASS 
         --version=${VERSION}
         --ignore="/^(nbproject.*|\.gitlab\-ci\.yml|\.phan.*|tests.*|phpunit\.xml)$/"
    only:
        refs:
            - master
